### ISSUE TITLE
CoreML -- AttributeError: 'torch._C.Node' object has no attribute 'ival'

### ISSUE THREAD

**Issue by MHGL** [DeepVAC/deepvac#112]
# **version**
- coreml == 4.1
- numpy == 1.20.5
- pytorch == 1.9.0

# **envirment**
- IMAGES: [gemfield/homepod: 2.0-pro](https://hub.docker.com/layers/gemfield/homepod/2.0-pro/images/sha256-a9d7a3b88b4cf1b03699fe9836d76103148739ad444e558b00d633fa9964ba1a?context=explore)
- GPU: GeForce GTX 1650
- DIRVER: Driver Version: 460.80
- CUDA: CUDA Version: 11.2

# **error**
```python3
Traceback (most recent call last):
  File "test.py", line 133, in <module>
    Yolov5Test(config)()
  File "/home/liyang/deepvac/deepvac/core/deepvac.py", line 306, in __call__
    self.export3rd()
  File "test.py", line 84, in export3rd
    super(Yolov5Test, self).export3rd(output_file)
  File "/home/liyang/deepvac/deepvac/core/deepvac.py", line 222, in export3rd
    export3rd(self.config, self.deepvac_config.cast, output_file)
  File "/home/liyang/deepvac/deepvac/cast/__init__.py", line 14, in export3rd
    caster(output_file)
  File "/home/liyang/deepvac/deepvac/cast/base.py", line 105, in __call__
    self.process(cast_output_file)
  File "/home/liyang/deepvac/deepvac/cast/coreml.py", line 60, in process
    coreml_model = coremltools.convert(model=model, inputs=[input], 
  File "/opt/conda/lib/python3.8/site-packages/coremltools/converters/_converters_entry.py", line 175, in convert
    mlmodel = mil_convert(
  File "/opt/conda/lib/python3.8/site-packages/coremltools/converters/mil/converter.py", line 128, in mil_convert
    proto = mil_convert_to_proto(model, convert_from, convert_to,
  File "/opt/conda/lib/python3.8/site-packages/coremltools/converters/mil/converter.py", line 171, in mil_convert_to_proto
    prog = frontend_converter(model, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/coremltools/converters/mil/converter.py", line 85, in __call__
    return load(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/load.py", line 70, in load
    converter = TorchConverter(torchscript, inputs, outputs, cut_at_symbols)
  File "/opt/conda/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/converter.py", line 146, in __init__
    self.graph = InternalTorchIRGraph(
  File "/opt/conda/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/internal_graph.py", line 241, in __init__
    new_node = InternalTorchIRNode(raw_node, parent=self)
  File "/opt/conda/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/internal_graph.py", line 140, in __init__
    self.attr = {
  File "/opt/conda/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/internal_graph.py", line 141, in <dictcomp>
    name: getattr(node, node.kindOf(name))(name)
AttributeError: 'torch._C.Node' object has no attribute 'ival'
```

# **reproduction**
- code: [yolov5](https://github.com/DeepVAC/yolov5)
- please refer to yolov5/CAST.md

# **reducection**
- pip install torch==1.8.1 will solve this

**Comment by MHGL** [comment]
#https://github.com/apple/coremltools/issues/1237

**Comment by MHGL** [comment]
apple/coremltools#1237

**Comment by MHGL** [comment]
#https://github.com/apple/coremltools/issues/1237

**Comment by MHGL** [comment]
https://github.com/apple/coremltools/issues/1237

**Comment by MHGL** [comment]
I get an exciting idea, i try to save freeze_model to disk, then use torch.jit.load get freeze_model before convert coreml, this problem not happened! like this:
```python3
import torch
import coremltools as ct

# init maxpool module
torch_model = torch.nn.Conv2d(3, 3, 1, 1)

# Trace with random data
example_input = torch.rand(1, 3, 224, 224) 
trace_model = torch.jit.trace(torch_model, example_input).eval()
freeze_model = torch.jit.freeze(trace_model)

# save freeze model to disk
freeze_model.save("tmp.trace.pt")
# get freeze_model from disk
freeze_model = torch.jit.load("tmp.trace.pt")

# Convert to Core ML using the Unified Conversion API
model = ct.convert(
    freeze_model,
    inputs=[ct.ImageType(name="input", shape=example_input.shape)], 
)
